version: "3"
services:
  influxdb:
    container_name: ${PROJECT_NAME}.influxdb
    image: influxdb:2.1.1-alpine
    volumes:
      - ./docker/influxdb/influxdb-config.yml:/etc/influxdb2/config.yml:ro
      - ./docker/influxdb/data:/var/lib/influxdb2/engine/data
    environment:
      DOCKER_INFLUXDB_INIT_USERNAME: ${DOCKER_INFLUXDB_INIT_USERNAME}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${DOCKER_INFLUXDB_INIT_PASSWORD}
      DOCKER_INFLUXDB_INIT_ORG: ${DOCKER_INFLUXDB_INIT_ORG}
      DOCKER_INFLUXDB_INIT_BUCKET: ${DOCKER_INFLUXDB_INIT_BUCKET}
      DOCKER_INFLUXDB_INIT_RETENTION: ${DOCKER_INFLUXDB_INIT_RETENTION}
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}
    ports:
      - 8086:8086
    networks:
      - monitoring
  telegraf:
    container_name: ${PROJECT_NAME}.telegraf
    image: telegraf:1.22.0-alpine
    volumes:
      - ./docker/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    ports:
      - 8125:8125
      - 8092:8092
      - 8094:8094
    depends_on:
      - influxdb
    networks:
      - monitoring
  php-fpm:
    container_name: ${PROJECT_NAME}.php-fpm
    image: php:8.1.4-fpm-alpine3.15
    volumes:
      - ./app/php-fpm:/app
    working_dir: /app
    environment:
      DOCKER_INFLUXDB_INIT_USERNAME: ${DOCKER_INFLUXDB_INIT_USERNAME}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${DOCKER_INFLUXDB_INIT_PASSWORD}
      DOCKER_INFLUXDB_INIT_ORG: ${DOCKER_INFLUXDB_INIT_ORG}
      DOCKER_INFLUXDB_INIT_BUCKET: ${DOCKER_INFLUXDB_INIT_BUCKET}
      DOCKER_INFLUXDB_INIT_RETENTION: ${DOCKER_INFLUXDB_INIT_RETENTION}
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}
    depends_on:
      - influxdb
      - mysql
    networks:
      - monitoring
  mysql:
    container_name: ${PROJECT_NAME}.mysql
    image: mysql:8.0.28
    volumes:
      - ./docker/mysql/config.cnf:/etc/mysql/conf.d/config.cnf:ro
      - ./docker/mysql/data:/var/lib/mysql
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - 3306:3306
    depends_on:
      - telegraf
    networks:
      - monitoring
networks:
  monitoring:
